In [8]:
import pandas as pd
import numpy as np

In [9]:
# Question 1
# What's the version of Pandas that you installed?

pd.__version__

'1.5.3'

In [10]:
# Question 2
# How many columns are in the dataset?


df = pd.read_csv('housing.csv')

# df.head()
# len(df.dtypes)
df.shape[1]

10

In [11]:
# Question 3
# Which columns in the dataset have missing values?

df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [12]:
# Question 4
# How many unique values does the ocean_proximity column have?

df['ocean_proximity'].nunique()

5

In [13]:
# Question 5
# What's the average value of the median_house_value for the houses located near the bay?

# df[df['ocean_proximity'] == "NEAR BAY"]
# df[df['ocean_proximity'] == "NEAR BAY"]['median_house_value']
# df[df['ocean_proximity'] == "NEAR BAY"]['median_house_value'].mean()

avr_value = df.groupby('ocean_proximity').median_house_value.mean()
avr_value['NEAR BAY']

259212.31179039303

In [25]:
# Question 6

#     Calculate the average of total_bedrooms column in the dataset.
#     Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
#     Now, calculate the average of total_bedrooms again.
#     Has it changed?

# Has it changed?

#     Hint: take into account only 3 digits after the decimal point.


avg_total_bedrooms = df['total_bedrooms'].mean()
print("avg_total_bedrooms:", avg_total_bedrooms)

df_filled = df['total_bedrooms'].fillna(avg_total_bedrooms)
avg_total_bedrooms_filled = df_filled.mean()
print("avg_total_bedrooms_filled:", avg_total_bedrooms_filled)

avg_total_bedrooms = float("{:.3f}".format(avg_total_bedrooms))
avg_total_bedrooms_filled = float("{:.3f}".format(avg_total_bedrooms_filled))

print("\nHas it changed? (only 3 digits): {}\nAverage of 'total_bedrooms': {}\nAverage of 'total_bedrooms' after fillna: {} ".format(avg_total_bedrooms != avg_total_bedrooms_filled, avg_total_bedrooms, avg_total_bedrooms_filled))

avg_total_bedrooms: 537.8705525375618
avg_total_bedrooms_filled: 537.8705525375617

Has it changed? (only 3 digits): False
Average of 'total_bedrooms': 537.871
Average of 'total_bedrooms' after fillna: 537.871 


In [36]:
# Question 7

#     Select all the options located on islands.
#     Select only columns housing_median_age, total_rooms, total_bedrooms.
#     Get the underlying NumPy array. Let's call it X.
#     Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
#     Compute the inverse of XTX.
#     Create an array y with values [950, 1300, 800, 1000, 1300].
#     Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
#     What's the value of the last element of w?

#     Note: You just implemented linear regression. We'll talk about it in the next lesson.

#     -1.4812
#     0.001
#     5.6992
#     23.1233


df.ocean_proximity.value_counts()
df_island = df[df['ocean_proximity'] == "ISLAND"]
df_island = df_island[['housing_median_age', 'total_rooms', 'total_bedrooms']]
df_island





housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [37]:
X = df_island.values
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [41]:
XTX = X.T.dot(X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [42]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [43]:
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [47]:
w = (XTX_inv.dot(X.T)).dot(y)
w

array([23.12330961, -1.48124183,  5.69922946])

In [48]:
w[-1]

5.699229455065575